version: "3.8"

services:
  build-wheel:
    volumes:
      - ./dist:/tmp/dist:rw

  install-wheel:
    volumes:
      - ./dist:/tmp/dist:r

  pre-commit:
    volumes:
      - ./model:/tmp/model:rw

  test:
    volumes:
      - ./model:/tmp/model:rw
