FROM timescale/timescaledb:2.5.0-pg14-oss as postgres
LABEL name=postgres
COPY ./docker-entrypoint.sh /usr/local/bin/
COPY ./sql/initdb.d/*.sql /docker-entrypoint-initdb.d/
COPY ./sql/patchdb.d/*.sql /docker-entrypoint-patchdb.d/
