ARG ROOT_CONTAINER=timescale/timescaledb:2.7.2-pg14-oss

FROM ${ROOT_CONTAINER} as postgres
LABEL name=postgres
COPY ./docker-entrypoint.sh /usr/local/bin/
COPY ./sql/initdb.d/*.sql /docker-entrypoint-initdb.d/
COPY ./sql/patchdb.d/*.sql /docker-entrypoint-patchdb.d/
